Feat: added new CI/CD workflows
enbox/enbox pull request #6
Opened 2020-04-21 22:26 UTC by 7automaton

Closes #5 

Added functionality for building and checking passing/failing builds, as well as deployment to web on push.

2020-04-21 22:30 UTC, anirudhb submitted a review, later dismissed

2020-04-21 22:30 UTC, anirudhb commented on .github/workflows/continuous-integration.yml
> +      if: ${{ runner.os == "Windows" }}
The if and the run should be on the same indent level
like this:
```yaml
- if: runner.os == "Windows"
  run: flutter config --enable-windows-desktop
```
Also note you can drop the `${{ }}` in if statements

2020-04-21 22:30 UTC, anirudhb commented on .github/workflows/continuous-integration.yml
> +    - run: flutter build web --release
You're not making a desktop binary? Also remember to upload the artifact.
And maybe put the `--enable-web` before the upgrade so you don't run it twice.

2020-04-22 00:29 UTC, anirudhb requested changes

2020-04-22 00:29 UTC, anirudhb commented on .github/workflows/continuous-integration.yml
> +        - if: ${{ runner.os == Windows }}
Inconsistent indentation. It should be like this instead:
```suggestion
        - name: Configure OS variables
          if: ${{ runner.os == Windows }}
          env:
            OS: windows
```

2020-04-22 00:29 UTC, anirudhb commented on .github/workflows/continuous-integration.yml
> +          path: dist
The build directory is called `build`

2020-04-22 04:48 UTC, 7automaton commented
Closes #8

2020-04-22 16:16 UTC, anirudhb requested changes

2020-04-22 16:16 UTC, anirudhb commented on .github/workflows/continuous-integration.yml
> +        if: ${{ runner.os == macOS }}
These have to be different items. It's supposed to be like this:
```suggestion
- if: runner.os == macOS
  env:
    OS: macos

2020-04-22 17:18 UTC, anirudhb approved these changes
Properly formatted

2020-04-22 17:18 UTC, merged